# Generated by Django 2.2.1 on 2019-05-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.CharField(max_length=255)),
                ('make_name', models.ManyToManyField(to='main_app.Make')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('make_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Make')),
                ('model_year', models.ManyToManyField(to='main_app.Year')),
            ],
        ),
    ]
