# Generated by Django 2.2.1 on 2019-05-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='make_name',
        ),
        migrations.AddField(
            model_name='make',
            name='model_year',
            field=models.ManyToManyField(to='main_app.Year'),
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='make_name',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make_name',
            field=models.ManyToManyField(to='main_app.Year'),
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='model_year',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Make'),
            preserve_default=False,
        ),
    ]
