# Generated by Django 2.2.1 on 2019-05-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190517_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='model_year',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='model_year',
            field=models.ManyToManyField(to='main_app.Year'),
        ),
    ]
