# Generated by Django 2.2.1 on 2019-05-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190517_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='model_year',
            field=models.IntegerField(),
        ),
    ]
